version: "3"
services:
  solarman-alerts:
    image: rameezk/solarman-mqtt
    restart: "always"
    network_mode: host
    environment:
      PYTHONUNBUFFERED: 1
      POLL_INTERVAL: 300
      SOLARMAN_USERNAME: "admin"
      SOLARMAN_PASSWORD: "admin"
      SOLARMAN_DEVICE_ID: "3991227239"
      SOLARMAN_SITE_ID: ""
      LOW_BATTERY_LEVEL: ""
      MQTT_BROKER_HOST: "192.168.1.150"
      MQTT_BROKER_PORT: "" # optional (defaults to 1883)
